##### Part 1

In [1]:
import numpy as np
from numpy import linalg as la

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$



$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\
2 & 1 & -1 & 1 \\
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\
-2\\
4
\end{matrix}
\end{pmatrix}$$

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\
0 & -1 & -1 & -5 \\
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\
-2\\
4
\end{matrix}
\end{pmatrix}$$

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
-x_{2}-x_{3}-5x_{4}=-2, \\
-2x_{3}+3x_{4}=4.
\end{cases}$$

$$x_{4} = c$$
$$-2x_{3}+3c = 4
\Rightarrow
x_{3}=-2+\frac{3c}{2}$$

$$-x_{2} - (-2+\frac{3c}{2})-5c = -2
\Rightarrow
x_{2} = 4-\frac{13c}{2}
$$

$$x_{1} + 4-\frac{13c}{2} - (-2+\frac{3c}{2}) - 2c = 0
\Rightarrow
x_{1} = 10c-6$$


__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2.
\end{cases}$



In [2]:
def solver(x, y):
    a_ext = np.append(x, y.T, axis=1)
    r_a = la.matrix_rank(x)
    r_a_ext = la.matrix_rank(a_ext)
    if r_a == r_a_ext and r_a == np.shape(x)[1]:
        print(f'Система определена, единственное решение')
    elif r_a == r_a_ext and r_a < np.shape(x)[1]:
        print(f'Система имеет бесконечное количество решений')
    else:
        print('Система несовместна, решений нет')

In [3]:
a = np.array([[3,-1,1],[2,-5,-3], [1,1,-1]])
b = np.array([[4,-17, 0]])

In [4]:
solver(a,b)

Система определена, единственное решение


In [5]:
a = np.array([[2,-4,6],[1,-2,3], [3,-6,9]])
b = np.array([[1,-2, 5]])

In [6]:
solver(a,b)

Система несовместна, решений нет


In [7]:
a = np.array([[1,2,5],[3,1,-8]])
b = np.array([[4,-2]])

In [8]:
solver(a,b)

Система имеет бесконечное количество решений



__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\
0 & 5 & 0 & 1\\
0 & 0 & 3 & 0\\
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$


In [9]:
a = np.array([[1,3,-2, 4],[0,5,0,1], [0,0,3,0], [0,0,0,2]])
b = np.array([[3, 2, 4, 1]])

In [10]:
solver(a,b)

Система определена, единственное решение



__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

По теореме Кроникера-Капелли система уравнений несовместна, если ранг матрицы коэффициентов меньше ранга расширенной матрицы.
Определим ранг матрицы коэффициентов.

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\
0 & -3 & -6\\
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\
b-4a\\
c-7a
\end{matrix}
\end{pmatrix}$$

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\
0 & -3 & -6\\
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\
b-4a\\
c-7a-2(b-4a)
\end{matrix}
\end{pmatrix}.$$

Ранг матрицы коэффициентов равен 2, соотвтетсвенно ранг расширенной матрицы должен быть больше двух и это возможно только в случае, когда выражение $(c-7a-2(b-4a)) \neq 0$.

 Найдем соотношение, при котором ранги матриц будут одинаковы приравняв получившееся выражение к 0.
 $$c-7a-2(b-4a) = 0
 \Rightarrow
 a-2b+c=0
 \Rightarrow
 c=2b-a$$
 Соответственно для всех соотношений $a$, $b$ и $c$, кроме $c=2b-a$ система уравнений несовместна.

##### Part 2

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$



In [11]:
a = np.array([[1, -2], [3, -4]])
b = np.array([[1,7]])
a, b

(array([[ 1, -2],
        [ 3, -4]]),
 array([[1, 7]]))

In [12]:
det_a = la.det(a)
det_a

2.0000000000000004

In [13]:
a_1 = np.array([[1, -2], [7, -4]])
a_2 = np.array([[1, 1], [3, 7]])
det_a_1 = la.det(a_1)
det_a_2 = la.det(a_2)

In [14]:
x_1 = det_a_1/det_a
x_2 = det_a_2/det_a
x_1, x_2

(4.999999999999998, 1.9999999999999991)

$$x_{1} = 5$$
$$x_{2} = 2$$

   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$


In [15]:
a = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([[10, -2, 1]])
a, b

(array([[ 2, -1,  5],
        [ 1,  1, -3],
        [ 2,  4,  1]]),
 array([[10, -2,  1]]))

In [16]:
det_a = la.det(a)
det_a

42.99999999999998

In [17]:
a_1 = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
a_2 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
a_3 = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])
det_a_1 = la.det(a_1)
det_a_2 = la.det(a_2)
det_a_3 = la.det(a_3)

In [18]:
x_1 = det_a_1/det_a
x_2 = det_a_2/det_a
x_3 = det_a_3/det_a
x_1, x_2, x_3

(2.0000000000000018, -1.0000000000000009, 1.0)

$$x_{1} = 2$$
$$x_{2} = -1$$
$$x_{3} = 1$$


__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\
2 & 9 & 12 \\
3 & 26 & 30
\end{pmatrix}$$



In [104]:
def lu_decompose(a):
    n = len(a)
    L = np.eye(len(a))
    U = np.zeros(np.shape(a))

    for i in range(n):

        # U
        for k in range(i, n):
            sum = 0
            for j in range(i):
                sum += (L[i][j] * U[j][k])
            U[i][k] = a[i][k] - sum

        # L
        for k in range(i, n):
            if i == k:
                continue
            else:
                sum = 0
                for j in range(i):
                    sum += (L[k][j] * U[j][i])

                L[k][i] = int((a[k][i] - sum) /
                              U[i][i])
    return L, U

In [106]:
a = np.array([[1,2,4],[2,9,12],[3,26,30]])
L, U = lu_decompose(a)
L

array([[1., 0., 0.],
       [2., 1., 0.],
       [3., 4., 1.]])

   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\
2 & 5 & 8 & 9\\
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

In [107]:
a = np.array([[1,1,2,4],[2,5,8,9],[3,18,29, 18], [4,22,53,33]])
L, U = lu_decompose(a)
L

array([[1., 0., 0., 0.],
       [2., 1., 0., 0.],
       [3., 5., 1., 0.],
       [4., 6., 7., 1.]])


__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$


In [108]:
a = np.array([[2,1,3], [11,7,5], [9,8,4]])
L, U = lu_decompose(a)
print(f'L = \n{L}')
print(f'U = \n{U}')

L = 
[[1. 0. 0.]
 [5. 1. 0.]
 [4. 2. 1.]]
U = 
[[  2.   1.   3.]
 [  0.   2. -10.]
 [  0.   0.  12.]]


$$Ly = b;$$
$$\begin{cases}
y_{1} = 1\\
5y_{1} + y_{2} = -6\\
4y_{1} + 2y_{2} + y_{3} = -5
\end{cases}$$
$$ y_{1} = 1, y_{2} = -11, y_{3} = 13$$

$$Ux = y;$$
$$\begin{cases}
2x_{1} + x_{2} + 3x_{3} = 1\\
2x_{2} - 10x_{3} = -11\\
12x_{3} = 13
\end{cases}$$

$$x_{1} = -1\frac{1}{12} , x_{2} = -\frac{1}{12}, x_{3} = 1\frac{1}{12}$$



__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$


$$l_{11} =\sqrt{a_{11}} = \sqrt{81} = 9$$
$$l_{21} =\frac{a_{21}}{l_{11}} = \frac{-45}{9} = -5$$
$$l_{31} =\frac{a_{31}}{l_{11}} = \frac{45}{9} = 5$$

$$l_{22} = \sqrt{a_{22}-l_{21}^{2}} = \sqrt{50 - (-5)^2} = 5$$
$$l_{32} = \frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right) = \frac{1}{5}(-15 - (-5) \cdot 5) = 2$$

$$l_{33} = \sqrt{a_{33}-l_{32}^{2}-l_{31}^{2}} = \sqrt{38 - 2^2 - 5^2} = 3$$

In [113]:
L = np.array([[9, 0, 0], [-5, 5, 0], [5, 2, 3]])
L

array([[ 9,  0,  0],
       [-5,  5,  0],
       [ 5,  2,  3]])

In [114]:
L.T

array([[ 9, -5,  5],
       [ 0,  5,  2],
       [ 0,  0,  3]])

$$Ly=b;$$
$$\begin{cases}
9y_{1} = 531\\
-5y_{1}+5y_{2}= -460\\
5y_{1} + 2y_{2} + 3y_{3} = 193
\end{cases}$$
$$ y_{1} = 59; y_{2} = -33; y_{3} = -12$$

$$L^{T}x=y;$$
$$\begin{cases}
9x_{1} - 5x_{2} + 5x_{3} = 59\\
5x_{2}+2x_{3}= -33\\
3x_{3} = -12
\end{cases}$$
$$ x_{1} = 6; x_{2} = -5; x_{3} = -4$$


__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.
###### Выполнено в пункте 2