In [11]:
import numpy as np
from numpy import linalg as la

a = np.array([[0,0,2,1], [0,0,2,2], [0,0,4,3], [2,3,5,6]])

##### Часть 1

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.


a) $A\cdot B$ и $B\cdot A$ - произведение не определено
б) $A\cdot B = C(5\times 5)$, $B\cdot A$ - произведение не определено
в) $A\cdot B = C(3\times 3)$, $B\cdot A = D(8\times 8)$
г) $A\cdot B = C(4\times 4)$, $B\cdot A = D(4\times 4)$

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\
0 & 5
\end{pmatrix}.$

$$A+B = \begin{pmatrix}
5 & -3\\
3 & 5
\end{pmatrix}$$

$$A\cdot B = \begin{pmatrix}
1\cdot4 + (-2)\cdot0 & 1\cdot(-1) + (-2)\cdot5\\
3\cdot4 + 0\cdot0 & 3\cdot(-1) + 0\cdot5
\end{pmatrix} = \begin{pmatrix}
4 & -11\\
12 & -3
\end{pmatrix}$$

$$B\cdot A = \begin{pmatrix}
4\cdot1 + (-1)\cdot3 & 4\cdot(-2) + (-1)\cdot0\\
0\cdot1 + 5\cdot3 & 0\cdot(-2) + 5\cdot0
\end{pmatrix} = \begin{pmatrix}
1 & -8\\
15 & 0
\end{pmatrix}$$


In [12]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
print(f'A + B = \n{a + b}\n')
print(f'AxB = \n{a @ b}\n')
print(f'BxA = \n{b @ a}')

A + B = 
[[ 5 -3]
 [ 3  5]]

AxB = 
[[  4 -11]
 [ 12  -3]]

BxA = 
[[ 1 -8]
 [15  0]]



__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\
1 & 1
\end{pmatrix}.$

$D = 3\times\begin{pmatrix}
1 & 7\\
3 & -6
\end{pmatrix} - 2\times\begin{pmatrix}
0 & 5\\
2 & -1
\end{pmatrix} + 4\times\begin{pmatrix}
2 & -4\\
1 & 1
\end{pmatrix}.$




$D =\begin{pmatrix}
3 & 21\\
9 & -18
\end{pmatrix} + \begin{pmatrix}
0 & -10\\
-4 & 2
\end{pmatrix} + \begin{pmatrix}
8 & -16\\
4 & 4
\end{pmatrix} = \begin{pmatrix}
11 & -5\\
-9 & -12
\end{pmatrix}$



In [13]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])
print(f'3A-2B+4C = \n{(3*a) + (-2*b) + (4*c)}')


3A-2B+4C = 
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\
5 & -2\\
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$$A^{T}=\begin{pmatrix}
4 & 5 & 2\\
1 & -2 & 3
\end{pmatrix}$$

$$A\cdot A^{T} =\begin{pmatrix}
4\cdot4 + 1\cdot1 & 4\cdot5 + 1\cdot(-2) & 4\cdot2 + 1\cdot3\\
5\cdot4 + (-2)\cdot1 & 5\cdot5 + (-2)\cdot(-2) & 5\cdot2 + (-2)\cdot3\\
2\cdot4 + 3\cdot1 & 2\cdot5 + 3\cdot(-2) & 2\cdot2 + 3\cdot3
\end{pmatrix}=\begin{pmatrix}
17 & 18 & 11\\
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}$$

$$A^{T}\cdot A =\begin{pmatrix}
4\cdot4 + 5\cdot5 + 2\cdot2 & 4\cdot1 + 5\cdot(-2) + 2\cdot3\\
1\cdot4 + (-2)\cdot5 + 3\cdot2 & 1\cdot1 +(-2)\cdot(-2) + 3\cdot3
\end{pmatrix}=\begin{pmatrix}
45 & 0\\
0 & 14
\end{pmatrix}$$

In [14]:
a = np.array([[4, 1], [5, -2], [2, 3]])
print(f'A x AT = \n{a @ a.T}\n')
print(f'AT x A = \n{a.T @ a}')

A x AT = 
[[17 18 11]
 [18 29  4]
 [11  4 13]]

AT x A = 
[[45  0]
 [ 0 14]]


##### Часть 2

__1.__ Вычислить определитель:

   a)
$$\begin{vmatrix}
sinx & -cosx\\
cosx & sinx
\end{vmatrix};$$

   б)
$$\begin{vmatrix}
4 & 2 & 3\\
0 & 5 & 1\\
0 & 0 & 9
\end{vmatrix};$$

   в)
$$\begin{vmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{vmatrix}.$$

a)
$$\begin{vmatrix}
sinx & -cosx\\
cosx & sinx
\end{vmatrix} = sinx\cdot sinx - (-cosx)\cdot cosx = 1$$

б)
$$\begin{vmatrix}
4 & 2 & 3\\
0 & 5 & 1\\
0 & 0 & 9
\end{vmatrix} = 4\cdot\begin{vmatrix}
5 & 1\\
0 & 9
\end{vmatrix} - 2\cdot\begin{vmatrix}
0 & 1\\
0 & 9
\end{vmatrix} + 3\cdot\begin{vmatrix}
0 & 5\\
0 & 0
\end{vmatrix} = 4\cdot(5\cdot9 - 0\cdot1) - 2\cdot(0\cdot9 - 0\cdot1) + 3\cdot(0\cdot0 - 0\cdot5) = 180
$$

In [24]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'|A| = {la.det(a):.0f}')


|A| = 180


в)
$$\begin{vmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{vmatrix} = 1\cdot\begin{vmatrix}
5 & 6\\
8 & 9
\end{vmatrix} - 2\cdot\begin{vmatrix}
4 & 6\\
7 & 9
\end{vmatrix} + 3\cdot\begin{vmatrix}
4 & 5\\
7 & 8
\end{vmatrix} = 4\cdot(5\cdot9 - 8\cdot6) - 2\cdot(4\cdot9 - 7\cdot6) + 3\cdot(4\cdot8 - 7\cdot5) = 0
$$

In [29]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'|A| = {la.det(a):.0f}')

|A| = -0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;

   б) $det(A^{T})$;

   в) $det(2A)$.


а) $det(A^{2}) = det(A\cdot A) = det(A) \cdot det(A) = 4 \cdot 4 = 16$

б) $det(A^{T})= det(A) = 4$, Исходя из свойтва определителя;

в) $det(2A) = 2^n \cdot det(A) = 2^n \cdot 4$, исходя из свойства умножения строки или столбца на константу. При умножении всей матрицы принимается во внимание её размерность (степень n).

__3.__  Доказать, что матрица

$\begin{pmatrix}
-2 & 7 & -3\\
4 & -14 & 6\\
-3 & 7 & 13
\end{pmatrix}$

вырожденная.


Матрица вырожденная при определителе = 0

$$\begin{vmatrix}
-2 & 7 & -3\\
4 & -14 & 6\\
-3 & 7 & 13
\end{vmatrix} = -2\cdot\begin{vmatrix}
-14 & 6\\
7 & 13
\end{vmatrix} - 7\cdot\begin{vmatrix}
4 & 6\\
-3 & 13
\end{vmatrix} - 3\cdot\begin{vmatrix}
4 & -14\\
-3 & 7
\end{vmatrix} = -2\cdot((-14)\cdot13 - 7\cdot6) - 7\cdot(4\cdot13 - (-3)\cdot6) - 3\cdot(4\cdot7 - (-3)\cdot(-14)) = 0
$$ Матрица вырожденная

In [30]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'|A| = {la.det(a):.0f}')

|A| = 0


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\
1 & 1 & 1\\
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\
0 & 0 & 2 & 2\\
0 & 0 & 4 & 3\\
2 & 3 & 5 & 6
\end{pmatrix}.$

a)
$\begin{pmatrix}
1 & 2 & 3\\
1 & 1 & 1\\
2 & 3 & 4
\end{pmatrix} = \begin{pmatrix}
1 & 2 & 3\\
1 & 1 & 1
\end{pmatrix} = \begin{pmatrix}
1 & 2 & 3\\
0 & -1 & -2
\end{pmatrix}
$
Ранг матрицы = 2


In [31]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Ранг матрицы = {la.matrix_rank(a)}')

Ранг матрицы = 2


б)
$\begin{pmatrix}
0 & 0 & 2 & 1\\
0 & 0 & 2 & 2\\
0 & 0 & 4 & 3\\
2 & 3 & 5 & 6
\end{pmatrix} = \begin{pmatrix}
0 & 0 & 2 & 1\\
0 & 0 & 2 & 2\\
2 & 3 & 5 & 6
\end{pmatrix} = \begin{pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\
0 & 0 & 2 & 2
\end{pmatrix} = \begin{pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\
0 & 0 & 0 & 1
\end{pmatrix}
$
Ранг матрицы = 3

In [32]:
a = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'Ранг матрицы = {la.matrix_rank(a)}')

Ранг матрицы = 3
