1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\
    0 & 0 & 5\\
    3 & -4 & 2\\
    1 & 6 & 5\\
    0 & 1 & 0
\end{pmatrix}.$$




In [34]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(precision=2, suppress=True)

In [25]:
a = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
a

array([[ 1,  2,  0],
       [ 0,  0,  5],
       [ 3, -4,  2],
       [ 1,  6,  5],
       [ 0,  1,  0]])

In [18]:
U, s, W = la.svd(a)

In [30]:
V = W.T
V

array([[ 0.07, -0.37, -0.93],
       [ 0.72,  0.67, -0.21],
       [ 0.69, -0.65,  0.31]])

In [31]:
D = np.zeros_like(a, dtype=float)
D[np.diag_indices(min(a.shape))] = s
D

array([[8.82, 0.  , 0.  ],
       [0.  , 6.14, 0.  ],
       [0.  , 0.  , 2.53],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ]])

In [29]:
print(U@D@W)

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]


2. Для матрицы из предыдущего задания найти:

а) евклидову норму;

По определению Евклидова норма совпадает с первым элементом на главной диагонали матрицы D

In [32]:
D[0][0]

8.824868854820444

In [36]:
# Проверим
la.norm(a, ord=2) == D[0][0]

True

б) норму Фробениуса.

In [38]:
# 1
la.norm(a, ord='fro')

11.045361017187261

In [45]:
#2
la.norm(a)

11.045361017187261

In [46]:
# 3
(sum([i**2 for i in a.flatten()]))**0.5

11.045361017187261

In [47]:
# 4
(sum([i**2 for i in D.flatten()]))**0.5

11.045361017187263